# Generated by Django 4.0 on 2021-12-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toAddress', models.CharField(max_length=50)),
                ('fromAddress', models.CharField(max_length=50)),
                ('arrivalTime', models.TimeField()),
                ('bufferMinutes', models.IntegerField()),
                ('nextTrip', models.DateField()),
                ('repeatsMonday', models.BooleanField()),
                ('repeatsTuesday', models.BooleanField()),
                ('repeatsWednesday', models.BooleanField()),
                ('repeatsThursday', models.BooleanField()),
                ('repeatsFriday', models.BooleanField()),
                ('repeatsSaturday', models.BooleanField()),
                ('repeatsSunday', models.BooleanField()),
                ('notificationEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
